licenses(["notice"])  # Apache 2.0

package(
    default_visibility = [
        "//tensorflow_compress:__subpackages__",
    ],
)

py_library(
    name = "python",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    visibility = ["//tensorflow_compress:__pkg__"],
    deps = [
        "//tensorflow_compress/python/layers",
    ],
)
